"""Add new fields to models

Revision ID: 16b062d78ee5
Revises: 0e7747135e35
Create Date: 2019-04-28 22:04:09.056944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16b062d78ee5'
down_revision = '0e7747135e35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('image_file', sa.String(length=20), nullable=True))
    op.add_column('comment', sa.Column('video_file', sa.String(length=20), nullable=True))
    op.add_column('pitch', sa.Column('video_file', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitch', 'video_file')
    op.drop_column('comment', 'video_file')
    op.drop_column('comment', 'image_file')
    # ### end Alembic commands ###
