"""empty message

Revision ID: ea13bc0e1d7d
Revises: 16b062d78ee5
Create Date: 2019-04-29 16:31:57.219615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea13bc0e1d7d'
down_revision = '16b062d78ee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('image', sa.String(length=20), nullable=True))
    op.drop_column('pitch', 'image_file')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('image_file', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('pitch', 'image')
    # ### end Alembic commands ###
